class DtcDescriptions {
  static const Map<String, String> _common = {
    'P0010': 'A Camshaft Position Actuator Circuit (Bank 1)',
    'P0011': 'A Camshaft Position - Timing Over-Advanced (Bank 1)',
    'P0012': 'A Camshaft Position - Timing Over-Retarded (Bank 1)',
    'P0030': 'HO2S Heater Control Circuit (Bank 1, Sensor 1)',
    'P0100': 'Mass or Volume Air Flow Circuit Malfunction',
    'P0101': 'Mass or Volume Air Flow Circuit Range/Performance',
    'P0102': 'Mass or Volume Air Flow Circuit Low Input',
    'P0103': 'Mass or Volume Air Flow Circuit High Input',
    'P0110': 'Intake Air Temperature Circuit Malfunction',
    'P0111': 'Intake Air Temperature Circuit Range/Performance',
    'P0112': 'Intake Air Temperature Circuit Low Input',
    'P0113': 'Intake Air Temperature Circuit High Input',
    'P0115': 'Engine Coolant Temperature Circuit Malfunction',
    'P0116': 'Engine Coolant Temperature Circuit Range/Performance',
    'P0117': 'Engine Coolant Temperature Circuit Low Input',
    'P0118': 'Engine Coolant Temperature Circuit High Input',
    'P0120': 'Throttle/Pedal Position Sensor/Switch A Circuit Malfunction',
    'P0121': 'Throttle Position Sensor/Switch A Circuit Range/Performance',
    'P0122': 'Throttle Position Sensor/Switch A Circuit Low Input',
    'P0123': 'Throttle Position Sensor/Switch A Circuit High Input',
    'P0125': 'Insufficient Coolant Temp for Closed Loop Fuel Control',
    'P0128': 'Coolant Thermostat - Temp Below Regulating Temp',
    'P0130': 'O2 Sensor Circuit (Bank 1, Sensor 1)',
    'P0131': 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)',
    'P0132': 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)',
    'P0133': 'O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)',
    'P0134': 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 1)',
    'P0135': 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)',
    'P0136': 'O2 Sensor Circuit (Bank 1, Sensor 2)',
    'P0137': 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)',
    'P0138': 'O2 Sensor Circuit High Voltage (Bank 1, Sensor 2)',
    'P0140': 'O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 2)',
    'P0141': 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)',
    'P0150': 'O2 Sensor Circuit (Bank 2, Sensor 1)',
    'P0170': 'Fuel Trim Malfunction (Bank 1)',
    'P0171': 'System Too Lean (Bank 1)',
    'P0172': 'System Too Rich (Bank 1)',
    'P0173': 'Fuel Trim Malfunction (Bank 2)',
    'P0174': 'System Too Lean (Bank 2)',
    'P0175': 'System Too Rich (Bank 2)',
    'P0200': 'Injector Circuit Malfunction',
    'P0201': 'Injector Circuit Malfunction - Cylinder 1',
    'P0202': 'Injector Circuit Malfunction - Cylinder 2',
    'P0203': 'Injector Circuit Malfunction - Cylinder 3',
    'P0204': 'Injector Circuit Malfunction - Cylinder 4',
    'P0205': 'Injector Circuit Malfunction - Cylinder 5',
    'P0206': 'Injector Circuit Malfunction - Cylinder 6',
    'P0218': 'Transmission Over Temperature Condition',
    'P0220': 'Throttle/Pedal Position Sensor/Switch B Circuit Malfunction',
    'P0300': 'Random/Multiple Cylinder Misfire Detected',
    'P0301': 'Cylinder 1 Misfire Detected',
    'P0302': 'Cylinder 2 Misfire Detected',
    'P0303': 'Cylinder 3 Misfire Detected',
    'P0304': 'Cylinder 4 Misfire Detected',
    'P0305': 'Cylinder 5 Misfire Detected',
    'P0306': 'Cylinder 6 Misfire Detected',
    'P0307': 'Cylinder 7 Misfire Detected',
    'P0308': 'Cylinder 8 Misfire Detected',
    'P0325': 'Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)',
    'P0326': 'Knock Sensor 1 Circuit Range/Performance (Bank 1)',
    'P0335': 'Crankshaft Position Sensor A Circuit Malfunction',
    'P0336': 'Crankshaft Position Sensor A Circuit Range/Performance',
    'P0340': 'Camshaft Position Sensor Circuit Malfunction',
    'P0341': 'Camshaft Position Sensor Circuit Range/Performance',
    'P0401': 'Exhaust Gas Recirculation Flow Insufficient Detected',
    'P0402': 'Exhaust Gas Recirculation Flow Excessive Detected',
    'P0411': 'Secondary Air Injection System Incorrect Flow Detected',
    'P0420': 'Catalyst System Efficiency Below Threshold (Bank 1)',
    'P0421': 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
    'P0430': 'Catalyst System Efficiency Below Threshold (Bank 2)',
    'P0440': 'Evaporative Emission Control System Malfunction',
    'P0441': 'EVAP Emission Control System Incorrect Purge Flow',
    'P0442': 'Evaporative Emission Control System Leak Detected (Small)',
    'P0443': 'Evaporative Emission Control System Purge Control Valve Circuit Malfunction',
    'P0446': 'EVAP Emission Control System Vent Control Circuit Malfunction',
    'P0455': 'Evaporative Emission Control System Leak Detected (Large)',
    'P0456': 'EVAP Emission Control System Leak Detected (Very Small)',
    'P0500': 'Vehicle Speed Sensor Malfunction',
    'P0505': 'Idle Control System Malfunction',
    'P0506': 'Idle Control System RPM Lower Than Expected',
    'P0507': 'Idle Control System RPM Higher Than Expected',
    'P0560': 'System Voltage Malfunction',
    'P0562': 'System Voltage Low',
    'P0563': 'System Voltage High',
    'P0600': 'Serial Communication Link Malfunction',
    'P0601': 'Internal Control Module Memory Check Sum Error',
    'P0602': 'Control Module Programming Error',
    'P0603': 'Internal Control Module Keep Alive Memory (KAM) Error',
    'P0606': 'PCM Processor Fault',
    'P0700': 'Transmission Control System Malfunction',
    'P0705': 'Transmission Range Sensor Circuit Malfunction',
    'P0715': 'Input/Turbine Speed Sensor Circuit Malfunction',
    'P0720': 'Output Speed Sensor Circuit Malfunction',
    'P0740': 'Torque Converter Clutch Circuit Malfunction',
    'P0750': 'Shift Solenoid A Malfunction',
    'C0035': 'Left Front Wheel Speed Sensor Circuit',
    'C0040': 'Right Front Wheel Speed Sensor Circuit',
    'C0050': 'Left Rear Wheel Speed Sensor Circuit',
    'C0055': 'Right Rear Wheel Speed Sensor Circuit',
    'B0001': 'Driver Frontal Stage 1 Deployment Control',
    'B1318': 'Battery Voltage Low',
    'U0001': 'High Speed CAN Communication Bus',
    'U0100': 'Lost Communication With ECM/PCM A',
    'U0101': 'Lost Communication With TCM',
    'U0121': 'Lost Communication With Anti-Lock Brake System (ABS) Control Module',
    'U0140': 'Lost Communication With Body Control Module',
    'U0155': 'Lost Communication With Instrument Panel Cluster (IPC) Control Module',
  };

  static String lookup(String code) {
    return _common[code.toUpperCase()] ?? _genericDescription(code);
  }

  static String _genericDescription(String code) {
    if (code.isEmpty) return 'Unknown trouble code';
    switch (code[0].toUpperCase()) {
      case 'P':
        return 'Powertrain trouble code (manufacturer-specific or rare generic).';
      case 'C':
        return 'Chassis trouble code.';
      case 'B':
        return 'Body trouble code.';
      case 'U':
        return 'Network/communication trouble code.';
      default:
        return 'Unknown trouble code.';
    }
  }
}
